config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/home'
  get 'game/:game_id/skip-card', :to => 'games#skip_card', :as => :skip_card
  get 'game/:game_id/pick-a-card', :to => 'games#pick_a_card', :as => :pick_a_card
  post '/games/setup-game', :to => 'games#setup_game', :as => :setup_game
  get '/game/statistics', :to => 'games#statistics', :as => :game_statistics

  root 'dashboards#home'

end

app/models/card.rb
class Card < ActiveRecord::Base

	INITIAL_CARDS_SET = Card.all * 24

	validates_presence_of :name, :points

	def card_name
		if name.to_i == 0
			name.first
		else
			name.to_i
		end
	end
end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :steps

	validates_presence_of :player_score, :dealer_score, :player_id, :player_bet

	def self.compute_game_won_by(player_score, dealer_score)
		if player_score > 21 or dealer_score == 21
			"dealer"
		elsif player_score == 21 or dealer_score > 21
			"player"
		else
			nil
		end
	end
end		

app/models/step.rb
class Step < ActiveRecord::Base
	belongs_to :game
	belongs_to :card

	validates_presence_of :game_id, :card_id, :card_drawn_by
	validates :card_drawn_by, :inclusion => { :in => ['player', 'dealer']}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def home
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  	
  	before_action :set_game, :except => :setup_game
    before_action :set_user_games, :except => [:setup_game]
  	before_action :game_open_check, :only => [:skip_card, :pick_a_card]
    def setup_game
		cookies[:player_id] = cookies[:player_id].present? ? cookies[:player_id] : Game.last.try(:player_id).present? ? Game.last.try(:player_id) + 1 : 1
  		@dealer_cards = [Card::INITIAL_CARDS_SET.sample]
  		@player_cards = 2.times.map { Card::INITIAL_CARDS_SET.sample }
  		
  		player_score = @player_cards.map(&:points).map{|card_point| card_point.to_i}.sum
  		dealer_score = @dealer_cards.map(&:points).map{|card_point| card_point.to_i}.sum

  		@game = Game.create(:player_score => player_score, :dealer_score => dealer_score, :player_id => cookies[:player_id], :player_bet => params[:game][:player_bet], :game_won_by => Game.compute_game_won_by(player_score, dealer_score))

  		Step.create([{:game_id => @game.id, :card_id => @dealer_cards.first.id, :card_drawn_by => 'dealer'}, 
  			{:game_id => @game.id, :card_id => @player_cards.first.id, :card_drawn_by => 'player'}, 
  			{:game_id => @game.id, :card_id => @player_cards.last.id, :card_drawn_by => 'player'}
  		])
        @user_games = Game.where(:player_id => @game.player_id)

  	end

  	def statistics
        @games = @user_games.last(4)
        @player_cards = Step.where(:card_drawn_by => 'player', :game_id => @games.map(&:id)).map{|step| step.card }
        @dealer_cards = Step.where(:card_drawn_by => 'dealer', :game_id => @games.map(&:id)).map{|step| step.card }
  	end

  	def skip_card
  		cards_left_in_deck = Card::INITIAL_CARDS_SET - @game.steps.map{|step| step.card } 
  		player_score = @game.player_score
  	
  		begin
  			new_card = cards_left_in_deck.sample	
  			cards_left_in_deck.delete(new_card)
  			Step.create(:game_id => @game.id, :card_id => new_card.id, :card_drawn_by => 'dealer')
  		end while Step.where(:card_drawn_by => 'dealer', :game_id => @game.id).map{|step| step.card.points.to_i}.sum <= 16

  		@player_cards = @game.steps.group_by(&:card_drawn_by)["player"].map{|dealer_step| dealer_step.card}
  		@dealer_cards = Step.where(:card_drawn_by => 'dealer', :game_id => @game.id).map{|step| step.card }
  		dealer_score = @dealer_cards.map(&:points).map{|card_point| card_point.to_i}.sum

  		game_won_by = if Game.compute_game_won_by(player_score.to_i, dealer_score).nil? && dealer_score >= 17
  			player_score.to_i > dealer_score ? "player" : "dealer"
  		else 
  			Game.compute_game_won_by(player_score.to_i, dealer_score)
  		end
  		
  		@game.update_attributes(:dealer_score => dealer_score,   :game_won_by => game_won_by)
  		render :setup_game
  	end

  	def pick_a_card
        cards_left_in_deck = Card::INITIAL_CARDS_SET - @game.steps.map{|step| step.card }
  		new_card = cards_left_in_deck.sample
  		player_score = @game.player_score.to_i + new_card.points.to_i
  		dealer_score = @game.dealer_score.to_i

  		@game.update_attributes(:player_score => player_score, :game_won_by => Game.compute_game_won_by(player_score, dealer_score))
  		Step.create(:game_id => @game.id, :card_id => new_card.id, :card_drawn_by => 'player')

  		@player_cards = Step.where(:card_drawn_by => 'player', :game_id => @game.id).map{|step| step.card }
  		@dealer_cards = Step.where(:card_drawn_by => 'dealer', :game_id => @game.id).map{|step| step.card }

  		render :setup_game
  	end

  	private
  	def set_game
  		@game = Game.find_by_id(params[:game_id])
  	end

    def set_user_games
      @user_games = Game.where(:player_id => cookies[:player_id])
    end

    def game_open_check
        if Game.compute_game_won_by(@game.player_score.try(:to_i), @game.dealer_score.try(:to_i)).present?
            redirect_to root_url, :notice => "#{@game.game_won_by.capitalize} has already won the game."
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
        base_title = "Blackjack Game"
        if page_title.empty?
            " #{base_title}"
        else 
            "#{page_title} | #{base_title}"
        end
    end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/games_helper.rb
module GamesHelper

	def get_player_winnings
	 	games_won_by_player = @user_games.group_by(&:game_won_by)['player']
		games_won_by_player.present? ? games_won_by_player.map{|game| game.player_bet.to_i}.sum : "0"
	end

	def get_player_total_bet
		@user_games.map{|game| game.player_bet.to_i}.sum
	end
end

app/views/dashboards/home.html.erb
<div style="clear: both;"></div>
<div class="container">
	<center><h1>Play Blackjack for Free</h1></center>
	<p>
		<h3>Rules & point System</h3>
		<ul>
			<li>Number cards (2 to 10) has a point value equal to the number on the card.</li>
			<li>Ace: 11 points.</li>
			<li>Jack/Queen/King: 10 points.</li>
			<li>The player plays the game against the dealer.</li>	
			<li>Aim of the player and the dealer is to get the maximum score <= 21.</li>
			<li>A score of exactly 21 is called Black Jack.</li>
			<li>A score of > 21 is bust.</li>
		</ul>
	</p>	
</div>

<div style="margin-top: 5%;" class="game-box">
	<%= form_tag setup_game_path, :method => 'post'  do %>
	<%= number_field_tag 'game[player_bet]', '#', :placeholder => 'Player Bet', :required => true, :class => 'player-bet' %>
	<br /><br />
	<%= submit_tag 'Start Game', :class=> "action-button mustard-button start-button" %>
	<% end %>

</div>

app/views/games/_basic_game.html.erb
<% provide(:page_title, "#{params[:action].gsub('_', ' ').titleize} | Game# #{@game.id}") %>

<script type="text/javascript">
	$(document).ready(function(){
		$('.game-box').css("height", "330px");					
	})
</script>
<p>Player ID: <%= @game.player_id %></p>
<p>Player Total Bet: $<%= get_player_total_bet %></p>
<p>Player Total Winnings: $<%= get_player_winnings %></p>
<br />
<div class = "col-lg-12">
	<% ['dealer', 'player'].each do |player_type| %>
		<div class="col-lg-5">

			<div class = '<%= "#{player_type}-box" %>'>
				<p class= '<%= "name-box #{player_type}-name-box"%>'><%= player_type.capitalize %></p>
				<br />
				<% instance_variable_get("@#{player_type}_cards").each do |card| %>
					<p class = '<%= "card-box #{player_type}-card-box"%>'><%= card.card_name %></p>
				<% end %>
				
				<% if player_type == 'player' && @game.player_score.to_i < 21 && @game.game_won_by.nil? %>
					<br />
					<%= link_to 'Pick a card', pick_a_card_path(@game.id), :class =>"action-button pick-card-button" %>
					<%= link_to 'Skip', skip_card_path(@game.id), :class => "action-button skip-button" %>
				<% end %>
			</div>
		</div>
	<% end %>	

	<% if @game.game_won_by.present? %>	
		<div style="margin-top: 50px;" class="col-lg-12">
			<script type="text/javascript">
				$(document).ready(function(){
					$('.game-box').css("height", "600px").css('margin-top', '5%');					
				})
			</script>
			<div class="result-box">
				<div style="margin-bottom: 50px;" class="col-lg-12">
					<button class="info-button player-wins-box" id="pick-card"><%= @game.game_won_by.capitalize %> Wins!</button>
				</div>
				<br />
				<div class="col-lg-5">
					<%= link_to 'Deal Again', '/dashboards/home', :class=> "action-button mustard-button" %>
				</div>
				<div class="col-lg-5">
					<%= link_to 'Statistics', '/game/statistics', :class=>"action-button statistics-button" %>
				</div>
			</div>
		</div>
	<% end %>

</div>

app/views/games/_statistics_table.html.erb
<center>
	<h2 class = "statistics-header">Last Four Games Statistics</h2>
	<% if @games.present? %>
		<table class = "statistics-table">
			<tr>
				<th></th>
				<% @games.each_with_index do |game, index| %>
					<th style = "color: yellow;">Game <%= index+ 1 %></th>
				<% end %>
			</tr>
			<tr>
				<td class = "dealer-row">Dealer</td>
				<% @games.each do |game| %>
					<td style = '<%= game.game_won_by == "dealer" ?  "color: #1de443;" : "color: #8a969a;" %>'><%= game.dealer_score %></td>
				<% end %>
			</tr>
			<tr>
				<td class = "player-row">Player</td>
				<% @games.each do |game| %>
					<td style = '<%= game.game_won_by == "player" ? "color: #1de443;" : "color: #8a969a;" %>'><%= game.player_score %></td>
				<% end %>
			</tr>
		</table>
	<% else %>
		<center><p>Data Not Available</p></center>
	<% end %>
<br />

<center><%= link_to 'Deal Again', '/dashboards/home', :class=> "action-button mustard-button" %></center>

app/views/games/setup_game.html.erb
<div class="game-box">
	<%= render :partial => 'basic_game' %>
</div>

app/views/games/statistics.html.erb
<% provide(:page_title, "#{params[:action].gsub('_', ' ').titleize}") %>
<div class="game-box">
	<p>Player Total Bet: $<%= get_player_total_bet %></p>
	<p>Player Total Winnings: $<%= get_player_winnings %></p>
	<%= render :partial => 'statistics_table' %>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('.game-box').css("height", "300px");					
	})
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= raw(full_title(yield(:page_title))) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults %>
  
  <%= csrf_meta_tags %>


</head>
<body>
<% if notice %>
	<p style="color: green; text-align: center;"><%= notice %>
<% end %>
<%= yield %>

</body>
</html>